export interface ServiceDetail {
  slug: string;
  title: string;
  headline: string;
  description: string;
  techStack: string[];
  benefits: string[];
  features: string[];
}

export const servicesDetailsMap: Record<string, ServiceDetail> = {
  "custom-software": {
    slug: "custom-software",
    title: "Custom Software Development",
    headline: "Bespoke digital architecture built to streamline operations and trigger enterprise growth.",
    description: "We engineer customized, proprietary software architectures tailored to solve your specific technical challenges and administrative workflows.",
    techStack: ["Next.js", "Node.js (TypeScript)", "PostgreSQL", "Tailwind CSS", "REST/GraphQL APIs"],
    benefits: ["100% Owned Source Code", "Tailored to Your Core Workflow", "Scale to Millions of Users", "High-Security Standards"],
    features: ["Custom Dashboard Design", "End-to-End API Integrations", "Database Architecture Setup", "Enterprise Security Audit"],
  },
  "frontend-development": {
    slug: "frontend-development",
    title: "Front-End Development",
    headline: "Responsive, ultra-fast, and premium user experiences powered by modern frameworks.",
    description: "We translate wireframes and Figma designs into pixel-perfect, highly accessible, and performance-optimized React/Next.js interfaces.",
    techStack: ["Next.js", "React", "TypeScript", "Tailwind CSS", "GSAP Animations", "Framer Motion"],
    benefits: ["Ultra-Fast Load Times", "Pixel-Perfect Layouts", "Fully Responsive (Mobile-First)", "Search Engine Optimized (SEO)"],
    features: ["SPA & SSR Rendering", "Dynamic Layout Adaptations", "Subtle UI Micro-animations", "W3C Standards Compliance"],
  },
  "backend-development": {
    slug: "backend-development",
    title: "Back-End Development",
    headline: "Scalable, secure, and robust microservices to run your enterprise data layers.",
    description: "We design robust servers, secure database engines, automated job queues, and advanced third-party API integrations.",
    techStack: ["Node.js", "Express / NestJS", "TypeScript", "PostgreSQL / MongoDB", "Redis Caching", "Docker"],
    benefits: ["Sub-Millisecond API Responses", "High Concurrent User Capacity", "Data Reliability & Backups", "Secure Authentication & JWT"],
    features: ["RESTful & GraphQL API Design", "Job Queue & Task Scheduling", "Relational Database Modelling", "Third-Party Payment Gateways"],
  },
  "web-applications": {
    slug: "web-applications",
    title: "Web Application Development",
    headline: "Feature-rich web applications built to convert users and power SaaS operations.",
    description: "We create secure, cloud-enabled web portals with interactive telemetry and responsive dashboards.",
    techStack: ["React", "Next.js", "Node.js", "PostgreSQL", "Stripe API", "Socket.io"],
    benefits: ["Cross-Platform Web Access", "Robust Admin Management Panels", "Real-Time Telemetry Data Updates", "Automated User Onboarding Flows"],
    features: ["Real-Time User Dashboards", "Billing & Invoice Generation", "Role-Based Access Control (RBAC)", "Activity Logging & Audit Trail"],
  },
  "mobile-apps": {
    slug: "mobile-apps",
    title: "Mobile App Development",
    headline: "Native iOS and Android mobile solutions built for speed and engagement.",
    description: "We develop high-performance cross-platform mobile apps using React Native, designed for fluid animations and offline capability.",
    techStack: ["React Native", "Expo", "TypeScript", "Redux Toolkit", "Push Notifications API"],
    benefits: ["Unified Codebase for iOS & Android", "App Store & Play Store Deployment", "Offline-First Data Syncing", "High User Engagement Features"],
    features: ["Biometric Authentication", "Push Notification Campaigns", "Geo-Location & Maps Setup", "Camera & Media Integrations"],
  },
  "saas-platforms": {
    slug: "saas-platforms",
    title: "SaaS Platform Development",
    headline: "Scalable multi-tenant recurring platforms engineered to monetize.",
    description: "We architect multi-tenant SaaS engines featuring automatic workspace subdomains, Stripe subscription plans, and seat management.",
    techStack: ["Next.js", "NestJS", "PostgreSQL", "Stripe Billing", "AWS ECS", "Auth0 / NextAuth"],
    benefits: ["Recurring Revenue Infrastructure", "Multi-Tenant Data Isolation", "Flexible Billing Frequency", "Robust Developer Sandbox APIs"],
    features: ["Automatic Subdomain Routing", "Stripe Checkout & Billing Portal", "Seat & License Management", "SaaS Usage Analytics"],
  },
  "database-solutions": {
    slug: "database-solutions",
    title: "Database Solutions",
    headline: "Secure relational and non-relational database architectures.",
    description: "We design optimal database schemas, implement replication strategies, and configure secure backups.",
    techStack: ["PostgreSQL", "MySQL", "MongoDB", "Redis", "Supabase", "Prisma ORM"],
    benefits: ["Zero-Data-Loss Reliability", "Optimized Query Performance", "High Availability Clusters", "GDPR / HIPAA Compliance"],
    features: ["Schema Design & Migration", "Read-Replication Config", "Encrypted Backups on AWS S3", "Data Partitioning & Sharding"],
  },
  "user-interfaces": {
    slug: "user-interfaces",
    title: "User Interface Design",
    headline: "Beautiful, interactive, and intuitive UI designs aligned with your brand.",
    description: "We design responsive, accessible, and stunning screens matching your core user personas and design system rules.",
    techStack: ["Figma Mockups", "Tailwind CSS", "Radix UI", "CSS variables", "Google Fonts"],
    benefits: ["Harmonious Color Systems", "Improved User Conversion Rates", "Accessible and WCAG Compliant", "Reusable UI Components"],
    features: ["Design System Foundations", "Wireframing & High-Fidelity Mockups", "Glassmorphic Theme Customization", "Interactive Clickable Prototypes"],
  },
  "web-development": {
    slug: "web-development",
    title: "Web Development Services",
    headline: "Bespoke marketing websites and corporate web portals.",
    description: "We craft fast-loading, highly discoverable corporate portals and business pages with premium animations.",
    techStack: ["Next.js (App Router)", "Tailwind CSS", "GSAP Animations", "Vercel Analytics", "SEO Meta Tags"],
    benefits: ["Top SEO Google Rankings", "Speed-Optimized Web Vitals", "Brand Authenticity & Authority", "Analytics & Conversion Tracking"],
    features: ["Dynamic Blog Layouts", "Interactive Canvas Visuals", "Contact Forms & Lead Capture", "Responsive Image Optimization"],
  },
  "cms-integration": {
    slug: "cms-integration",
    title: "CMS Integration",
    headline: "Friendly content management systems giving you complete layout control.",
    description: "We connect headless CMS engines to custom front-ends, enabling content editing without coding.",
    techStack: ["Sanity.io", "Strapi CMS", "Contentful", "GraphQL APIs", "Next.js ISR"],
    benefits: ["No-Code Editing for Marketers", "Incremental Static Regeneration", "Robust Markdown & Rich Text", "Flexible Content Modeling"],
    features: ["Headless CMS Setup", "Rich Text & Asset Upload Panels", "Webhook Integration for Auto-Builds", "Multi-Language Localization"],
  },
  "devops": {
    slug: "devops",
    title: "DevOps & Infrastructure",
    headline: "Automated server pipelines and secure cloud server operations.",
    description: "We set up zero-downtime deployment pipelines, monitor container health, and configure CDN layers.",
    techStack: ["Docker", "Kubernetes", "GitHub Actions", "Terraform", "NGINX / Vercel"],
    benefits: ["Zero-Downtime Releases", "Self-Healing Infrastructure", "Automated Rollbacks on Error", "Reduced Cloud Hosting Bills"],
    features: ["CI/CD Pipeline Construction", "Infrastructure as Code (IaC)", "Container Orchestration Setup", "SSL Certificate Automation"],
  },
  "cloud-architecture": {
    slug: "cloud-architecture",
    title: "Cloud Architecture",
    headline: "Reliable and high-availability cloud cluster designs.",
    description: "We architect multi-region server layouts on AWS, GCP, or Azure to ensure 99.99% system uptime.",
    techStack: ["AWS (S3, EC2, ECS)", "GCP Cloud Run", "Cloudflare DNS & CDN", "Serverless Functions"],
    benefits: ["Automatic Traffic Auto-Scaling", "Geographical Redundancy", "Highly Secure VPC Networks", "Pay-as-you-grow Cost Setup"],
    features: ["VPC Security Configurations", "Load Balancer Setup", "CDN Cache Optimization", "Serverless Infrastructure Designs"],
  },
  "database-optimization": {
    slug: "database-optimization",
    title: "Database Optimization",
    headline: "Eliminate performance bottlenecks and queries latency.",
    description: "We analyze database telemetry, optimize slow queries, add missing indexes, and set up Redis caching layer.",
    techStack: ["PostgreSQL Explain", "Redis Cache Layer", "Prisma Query Logs", "PgBouncer Connection Pooling"],
    benefits: ["Reduced Server CPU Load", "Faster Page Response Times", "Scale DB for Heavy Loads", "Optimal DB Query Executions"],
    features: ["Slow Query Analysis & Fixing", "Index Optimization Schemes", "Connection Pool Configuration", "Redis Cache Invalidation Rules"],
  },
  "qa-testing": {
    slug: "qa-testing",
    title: "Quality Assurance (SQA)",
    headline: "Comprehensive testing to ensure reliable user experiences.",
    description: "We write automated end-to-end tests, unit tests, and performance benchmark test sets.",
    techStack: ["Playwright / Cypress", "Jest / Vitest", "Lighthouse Benchmarks", "Postman API Tests"],
    benefits: ["Zero Regression bugs", "Verified Browser Cross-Compatibility", "Guaranteed Performance Metrics", "Reduced Customer Support Tickets"],
    features: ["E2E User Flow Tests", "Automated API Test Suites", "Load & Stress Performance Tests", "Manual Regression Checklists"],
  },
  "devops-automation": {
    slug: "devops-automation",
    title: "DevOps Automation",
    headline: "Remove manual tasks with automated release cycles.",
    description: "We build deployment triggers, Slack notifications on build status, and automatic package upgrades.",
    techStack: ["GitHub Actions", "Docker Compose", "Bash Scripts", "Slack / Discord Webhooks"],
    benefits: ["Save Engineering Hours", "Consistency in Deployments", "Instant Team Slack Alerts", "Safe Automated Version Bumps"],
    features: ["Auto-Build & Release Scripting", "Deployment Alert Systems", "Dependency Scan Automations", "Staging Environment Provisioning"],
  },
};
